export const LOAD_STUDENT=''
export const LOAD_STUDENT_SUCCESS='LOAD_STUDENT_SUCCESS'
export const LOAD_STUDENT_FAILURE='LOAD_STUDENT_FAILURE'

export const EDIT_STUDENT='EDIT_STUDENT'
export const EDIT_STUDENT_SUCCESS='EDIT_STUDENT_SUCCESS'
export const EDIT_STUDENT_FAILURE='EDIT_STUDENT_FAILURE'

export const ADD_STUDENT='ADD_STUDENT'
export const ADD_STUDENT_SUCCESS='ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE='ADD_STUDENT_FAILURE'

export const CLEAR_ERROR_MESSAGE='CLEAR_ERROR_MESSAGE'